### ISSUE TITLE
Bubble/circle packing chart

### ISSUE THREAD

**Issue by meganmckissack** [hackoregon/team-budget-frontend#7]
This is currently being worked in by David Able in [component-library issue#68](https://github.com/hackoregon/component-library/issues/68)

**Comment by meganmckissack** [comment]
done but currently in component-library pr

**Comment by meganmckissack** [comment]
David Abel had done great work on this, it's currently in a pr on the component library.  let's figure out how to use this in the budget team frontend without the component library if possible.  @palmerev cc: https://github.com/drabelpdx, until he's in the organization

**Comment by palmerev** [comment]
This has now been integrated into the budget frontend itself. Future work on this can go in separate issues.
